version: "3.8"
  
volumes:
    jenkins_data:

services:

  jenkins:
    image: jenkins-sandbox
    user: root
    build:
      context: .
    container_name: jenkins
    ports:
      - 8080:8080
      - 5000:5000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # docker in docker